# Day 6: NumPy Basics



## Goal: Learn arrays, indexing, vector ops.

**Deliverable:** Create and manipulate NumPy arrays.

In [4]:
import numpy as np
arr = np.arange(1,13)
arr = arr.reshape(4,3)
print(arr)
print('mean axis0', arr.mean(axis=0))
# TODO: normalize arr rows

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
mean axis0 [5.5 6.5 7.5]


### Exercises (TODO)
- Compute column-wise mean and std.
- Normalize each row to sum to 1.